diabetes-LinearRegression

In [13]:
# 데이터 처리(pandas), 수치 계산(numpy), 구글 드라이브 연동을 위한 라이브러리 import
import pandas as pd
import numpy as np
from google.colab import drive

drive.mount('/content/drive') # 구글 드라이브를 Colab에 연결(마운트)

path = '/content/drive/MyDrive/Colab Notebooks/diabetes.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
# DataFrame으로 읽기
df = pd.read_csv(path)
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [15]:
# Outcome 열을 제외한 새로운 DataFrame 생성
df2=df.drop('Outcome',axis=1)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [16]:
# BMI 열을 추출하고 값들의 개수를 확인한 뒤 전체 값 출력
y=df2['BMI']
y.value_counts()
y

0      33.6
1      26.6
2      23.3
3      28.1
4      43.1
       ...
763    32.9
764    36.8
765    26.2
766    30.1
767    30.4
Name: BMI, Length: 768, dtype: float64

In [17]:
# BMI 열을 제외한 입력 데이터(X)를 만들고 상위 5개 행 확인
X=df2.drop('BMI',axis=1)
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,0.627,50
1,1,85,66,29,0,0.351,31
2,8,183,64,0,0,0.672,32
3,1,89,66,23,94,0.167,21
4,0,137,40,35,168,2.288,33

In [18]:
# 데이터를 학습용(train)과 테스트용(test)으로 나누기 (25%는 테스트 데이터)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [19]:
# 라이브러리 import
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [20]:
model = LinearRegression()       # 선형 회귀 모델 생성
model.fit(X_train, y_train)      # 학습 데이터로 모델 학습
ly_preds = model.predict(X_test) # 테스트 데이터로 예측값 생성

print('평균제곱근오차', mean_squared_error(ly_preds, y_test))
# sklearn으로 MSE(평균제곱오차) 계산 및 출력

def mse_np(actual, predicted):
    return np.mean((np.array(actual) - np.array(predicted)) ** 2)
# numpy를 이용해 MSE 계산하는 함수 정의

print('평균제곱근오차', mse_np(ly_preds, y_test))
# numpy로 계산한 MSE 출력

def mse(actual, predicted):
    sum_square_error = sum((a - p) ** 2 for a, p in zip(actual, predicted))
    # 실제값과 예측값 차이를 제곱해서 모두 더함
    mean_square_error = sum_square_error / len(actual)
    # 전체 개수로 나눠 평균 계산
    return mean_square_error

print('평균제곱근오차', mse(ly_preds, y_test))

평균제곱근오차 52.23558099742443
평균제곱근오차 52.23558099742443
평균제곱근오차 52.23558099742445