**Titanic-classifier**

**(Logistic Regression, Decision Tree, Random Forest)**

In [31]:
# titanic.csv 파일을 불러와 df(DataFrame)에 저장

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [32]:
y=df['Survived']
y.value_counts()
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [33]:
from sklearn.preprocessing import LabelEncoder

# 1. 결측치 처리
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# 2. Label Encoding
le = LabelEncoder()

df['Name_encoded'] = le.fit_transform(df['Name'])
df['Sex_encoded'] = le.fit_transform(df['Sex'])
df['Embarked_encoded'] = le.fit_transform(df['Embarked'])

# 3. 원본 문자열 컬럼 제거
df = df.drop(['Name', 'Sex', 'Embarked', 'Ticket', 'Cabin'], axis=1)

# 4. X, y 분리
X = df.drop(['Survived'], axis=1)
X

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Name_encoded,Sex_encoded,Embarked_encoded
0,1,3,22.000000,1,0,7.2500,108,1,2
1,2,1,38.000000,1,0,71.2833,190,0,0
2,3,3,26.000000,0,0,7.9250,353,0,2
3,4,1,35.000000,1,0,53.1000,272,0,2
4,5,3,35.000000,0,0,8.0500,15,1,2
...,...,...,...,...,...,...,...,...,...
886,887,2,27.000000,0,0,13.0000,548,1,2
887,888,1,19.000000,0,0,30.0000,303,0,2
888,889,3,29.699118,1,2,23.4500,413,0,2
889,890,1,26.000000,0,0,30.0000,81,1,0
890,891,3,32.000000,0,0,7.7500,220,1,1

In [34]:
# 데이터를 학습용(train)과 테스트용(test)으로 나누기 (25%는 테스트 데이터)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [35]:
# 라이브러리 import

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import warnings

In [36]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0, max_iter=1000)   # 로지스틱 회귀 모델 생성(반복하는 최대 횟수 지정)
clf_lr.fit(X_train, y_train)                                 # 학습용 데이터로 모델 학습(fit)

pred_lr = clf_lr.predict(X_test)                             # 테스트 데이터로 예측 수행

print("--- Logistic Regression Classifier ---")
print(accuracy_score(y_test, pred_lr))                       # 예측 정확도 출력
print(confusion_matrix(y_test, pred_lr))                     # 혼동행렬(모델이 어디서 틀렸는지 보여주는 표) 출력

--- Logistic Regression Classifier ---
0.8116591928251121
[[119  20]
 [ 22  62]]

In [37]:
# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

--- Decision Tree Classifier ---
0.7309417040358744
[[106  33]
 [ 27  57]]

In [38]:
# Build a radom Forest classifier and predict

warnings.filterwarnings('ignore')

print ("--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

--- Radom Forest ---
0.852017937219731
[[127  12]
 [ 21  63]]

In [39]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# 1. Accuracy (전체 정확도, 전체 승객 맞춘 비율)
acc = accuracy_score(y_test, pred_lr)

# 2. Precision (정밀도, 살았다고 한 사람의 정확도)
precision = precision_score(y_test, pred_lr)

# 3. Recall (재현율, 실제 생존자를 얼마나 찾았는지)
recall = recall_score(y_test, pred_lr)

# 4. F1-score (균형 지표)
f1 = f1_score(y_test, pred_lr)

# 5. Confusion Matrix
cm = confusion_matrix(y_test, pred_lr)

# 6. 전체 리포트
report = classification_report(y_test, pred_lr)

# 출력
print("Accuracy:", acc)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", report)

Accuracy: 0.8116591928251121
Precision: 0.7560975609756098
Recall: 0.7380952380952381
F1-score: 0.7469879518072289

Confusion Matrix:
 [[119  20]
 [ 22  62]]

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.86      0.85       139
           1       0.76      0.74      0.75        84

    accuracy                           0.81       223
   macro avg       0.80      0.80      0.80       223
weighted avg       0.81      0.81      0.81       223